stages:
  - build-php

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

# Master
build-master-php:
  stage: build-php
  image: php:7.2
  before_script:
    - set -xe
    - apt-get update -yqq
    - apt-get install git wget zip unzip -yqq
    - 
    # Install Composer dependencies

    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (has_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer Verified'; } else { echo 'Installer Not Verified'; } ;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - docker-php-ext-install pdo_mysql
script:
  - cp .env.example .env
  - php composer.phar install --ignore-platform-reqs --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
  - php artisan key:generate
  - vendor/bin/phpunit

artifacts:
  paths:
    - ./vendor